---
# Defaults for role cis_level1

cis_auditd_rules_file: "/etc/audit/rules.d/99-cis.rules"
cis_sysctl_file: "/etc/sysctl.d/99-cis.conf"
cis_modprobe_file: "/etc/modprobe.d/99-cis-blacklist.conf"
cis_sshd_config_dir: "/etc/ssh/sshd_config.d"
cis_sshd_config_file: "/etc/ssh/sshd_config.d/00-cis.conf"
cis_issue_file: "/etc/issue"
cis_issue_net_file: "/etc/issue.net"
cis_motd_file: "/etc/motd"
cis_gdm_banner_file: "/etc/dconf/db/gdm.d/01-banner-message"
cis_gdm_profile_file: "/etc/dconf/profile/gdm"
