---
himmelblau_repo_baseurl: "https://packages.himmelblau-idm.org/stable/latest/rpm/rocky10"
himmelblau_repo_gpgkey: "https://packages.himmelblau-idm.org/himmelblau.asc"
himmelblau_repo_enabled: true
himmelblau_repo_gpgcheck: true

himmelblau_packages:
  - himmelblau
  - pam-himmelblau
  - nss-himmelblau
  - authselect
  - pam

himmelblau_domain: "jordangomes.com"
himmelblau_idmap_range: "200000-2000200000"
himmelblau_app_id: "4942b72d-1d20-4dea-ac8d-3504fe3547e4"
himmelblau_debug: false
himmelblau_pam_allow_groups: []

himmelblau_authselect_features:
  - "with-mfa"
  - "with-silent-lastlog"
  - "with-sudo"
  - "with-gdm"

himmelblau_sudo_groups:
  - name: "aad_linux_admins"
    spec: "ALL=(ALL) ALL"
  - name: "Linux-Admins"
    spec: "ALL=(ALL) ALL"
