---
himmelblau_repo_baseurl: "https://packages.himmelblau-idm.org/stable/latest/rpm/rocky10"
himmelblau_repo_gpgkey: "https://packages.himmelblau-idm.org/himmelblau.asc"
himmelblau_repo_enabled: true
himmelblau_repo_gpgcheck: true

himmelblau_packages:
  - himmelblau
  - pam-himmelblau
  - nss-himmelblau
  - authselect
  - pam

himmelblau_domain: "example.com"
himmelblau_idmap_range: "200000-2000200000"
himmelblau_app_id: ""
himmelblau_debug: false
himmelblau_pam_allow_groups: []

himmelblau_authselect_features:
  - "with-mfa"
  - "with-silent-lastlog"
  - "with-sudo"
  - "with-gdm"

himmelblau_sudo_groups: []
